import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { data } from "../constants";
import styles from "../styles/Home.module.css";
import { CompanySummary } from "../types";
import {
  getJobCategories,
  getJobNames,
  getPrimaryVertial,
  getSkills,
} from "../utils";

const Home: NextPage = () => {
  const summary: CompanySummary[] = data.companies.map((company) => ({
    name: company.name,
    country: company.country,
    primary_vertical: company.primary_vertical,
    tech_description: company.tech_description,
    website: company.website,
    jobs: company.jobs.map((j) => ({
      pretty_eng_type: j.pretty_eng_type,
      title: j.title,
      skills: j.skills.map((s) => s.name),
    })),
  }));

  const pV = getPrimaryVertial(summary);
  const jS = getSkills(summary);
  const jC = getJobCategories(summary);
  const jT = getJobNames(summary);

  console.log(summary.slice(10));

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button className="accordion">Primary verticals ({pV.length})</button>
        <ul className="panel">
          {pV
            .sort((a, b) => Number(b.occ) - Number(a.occ))
            .map((p) => (
              <li key={p.name}>{`${p.name}: ${p.occ}`}</li>
            ))}
        </ul>
        <button className="accordion">Skills ({jS.length})</button>
        <ul className="panel">
          {jS
            .sort((a, b) => Number(b.occ) - Number(a.occ))
            .map((skill) => (
              <li key={skill.name}>{`${skill.name}: ${skill.occ}`}</li>
            ))}
        </ul>
        <button className="accordion">Job categories ({jC.length})</button>
        <ul className="panel">
          {jC
            .sort((a, b) => Number(b.occ) - Number(a.occ))
            .map((title) => (
              <li key={title.name}>{`${title.name}: ${title.occ}`}</li>
            ))}
        </ul>
        <button className="accordion">Job titles ({jT.length})</button>
        <ul className="panel">
          {jT
            .sort((a, b) => Number(b.occ) - Number(a.occ))
            .map((title) => (
              <li key={title.name}>{`${title.name}: ${title.occ}`}</li>
            ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
